### ISSUE TITLE
Get Field Column Header text  

### ISSUE THREAD

**Issue by joaojmendes** [IBM/nodejs-idb-connector#116]
Please create a method to get column header of Field, at this moment we only have the:

statement.fieldName(index);

and 
maybe:
statement.FieldHeader(index)

Thank you!

**Comment by kadler** [comment]
What do you mean by field header?

**Comment by joaojmendes** [comment]
The possibility to get  the column header  defined for a column (COLHDG, DDS KEYWORD) for use  as column label in forms.

Thank you!

**Comment by dmabupt** [comment]
Hello @joaojmendes , Do you mean the `SQL_DESC_LABEL` attribute on https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/cli/rzadpfncolattrs.htm

**Comment by dmabupt** [comment]
Hello @joaojmendes , Did you mean the **label** for a column? [API link](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/cli/rzadpfncolattrs.htm).

SQL_DESC_LABEL | CHAR(128) | The label for this column, if one exists. Otherwise, a zero-length string.For this attribute to be retrieved, the attribute SQL_ATTR_EXTENDED_COL_INFO must have been set to SQL_TRUE for either the statement handle or the connection handle.
-- | -- | --

**Comment by joaojmendes** [comment]
Hi,

Yeah, seems that is it.  In syscolumns view the column is “COLUMN_HEADING”.

Thanks!

**Comment by dmabupt** [comment]
Currently we have some problems when calling the API SQLColAttribute to get the column label. I need to find some other solutions.
